### ISSUE TITLE
extract panorama

### ISSUE THREAD

**Issue by laufre** [BodenmillerGroup/imctools#100]
* imctools version: 0.0.4
* Python version: 3.8.3
* Operating System: Mac OS Big Sur

Hello,
We would like to extract the panorama from the .mcd file. What is the best way to do that? 
We tried mcdlib, but we had troubles installing it. It looks like the project mcdlib is no longer being supported, right?
Is there another way to extract the panorama, for example using imctools? It appears that imctools has implemented a class for panoramas, but it is not clear for us from the documentation how to use it.
Could you maybe provide an example how to extract a panorama from the mcd file?

I'm aware that the issue section is not meant for this kind of inquiry, do you provide any sort of forum (e.g. mailing list) for more open ended questions?
Thank you so much in advance!

**Comment by jwindhager** [comment]
Hi @laufre,

indeed, the mcdlib has been archived and is not maintained anymore in favor of imctools v2.

With imctools v2, extracting panorama images from .mcd files [should be straightforward using the McdParser class](https://github.com/BodenmillerGroup/imctools/blob/master/imctools/io/mcd/mcdparser.py#L139).

To my knowledge, with imtools v1, you could first save the panorama to a temporary directory using [McdParser.save_panorama}(https://github.com/BodenmillerGroup/imctools/blob/v1.x/imctools/io/mcdparserbase.py#L237) and then read in the image file manually. But maybe @votti or @plankter have better suggestions?

**Comment by votti** [comment]
I would  strictly recommend using Imctools v2 by now and use the `McdParser` class there: https://bodenmillergroup.github.io/imctools/io/mcd/mcdparser.html

To look into all the panoramas available, you should look into the attribute:
`McdParser.session.panoramas` which is a dictionary containing all `panoramas` and their metadata:
https://bodenmillergroup.github.io/imctools/data/panorama.html

For imctools v1 there is the direct way is to use McdParser.save_panorama.

**Comment by plankter** [comment]
In imctools v2 such functionality is also available. One can get/save slide/panoramas images:

https://bodenmillergroup.github.io/imctools/io/mcd/mcdparser.html#imctools.io.mcd.mcdparser.McdParser.save_panorama_image

**Comment by laufre** [comment]
Thank you for your answers, with your help I managed to extract the panoramas!
