### ISSUE TITLE
Make exceptions discoverable in API

### ISSUE THREAD

**Issue by afrendeiro** [BodenmillerGroup/imctools#101]
* imctools version: 2.1.0
* Python version: 3.8.6
* Operating System: Ubuntu 20.10

### Description

Hi, thanks for developing `imctools`. I'm updating a package which depends on it from v1 to v2.

I'm trying to get the `imctools.io.abstractparserbase.AcquisitionError` from v1 which was an error thrown by a specific MCD file a while ago and it would be great to find the exception without actually having and processing the file again.

Currently it's a little unclear to me where exceptions are defined. Perhaps there could be a centralized module `imctools.exceptions` or `imctools.errors` where all would be defined? If this module would also be added to the docs API it would make it much easier too.

Thanks!

**Comment by plankter** [comment]
The exception is still available in `imctools/io/errors.py` file, but it isn't used internally anymore because reading corrupted acquisitions should return None and not raise an exception. This is due to the fact that one MCD file can have both valid and invalid acquisitions and parsing such files shouldn't stop the execution.

**Comment by afrendeiro** [comment]
I see, so `Mcdparser.get_acquisition_data` will always return a `AcquisitionData` but it's `image_data` being `None` and the `is_valid` flag will reflect some error occurred.

I know it's a lot of effort and documentation is hard, but having return types annotated and raised exceptions documentation would be really great.

You guys fine with PRs?

**Comment by plankter** [comment]
Sure, you are welcome.
