### ISSUE TITLE
Extra 161 bytes extracted on all image buffers

### ISSUE THREAD

**Issue by wflynny** [BodenmillerGroup/imctools#102]
* imctools version: 2.1.0
* Python version: 3.8.5
* Operating System:  macOS Mojave 10.14.6

### Description

It looks like the methods to extract images from the binary format are pulling an extra 161 bytes at the end of the image.  For example, we expect a JPEG slide image to start with the bytes `\xff\xd8\xff...` and end with `\xff\xd9`.  PNGs and other image formats have similar start and stop byte sequences.  The code for extracting slide, panorama, before-ablation, and after-ablation images all add `image_offset_fix` to both the `img_start` and `img_end` when I think it should only be added to the start.

This isn't super critical as most image readers will just truncate the extra bytes, but I've been using imctools to access/modify the image bytes in place. 

### What I Did

Here's a test:

```{python}
from imctools.io.mcd.mcdparser import McdParser

IMAGE_BOOKENDS = {
    "PNG": (b"\x89\x50\x4e\x47", b"\x49\x45\x4e\x44\xae\x42\x60\x82"),
    "JPEG": (b"\xff\xd8\xff", b"\xff\xd9")
}

def _infer_bookends(buf):
    for key, (start, end) in IMAGE_BOOKENDS.items():
        if not buf.startswith(start):
            continue
        i0 = buf.index(start)
        i1 = buf.index(end) + len(end) + 1
        ex = len(buf) - i1 + i0
        print(f"Buffer of length {len(buf)} contains a {key} from {i0} to {i1} ({ex} extra bytes)")
        break
    else:
        print("This buffer doesn't start with a known byte set")
        
def test_mcd_image_offsets(mcd):
    for name, method in (
        ("Slide", mcd.get_slide_image),
        ("Panorama", mcd.get_panorama_image),
        ("Before_Ab", mcd.get_before_ablation_image),
        ("After_Ab", mcd.get_after_ablation_image),
    ):
        print(name)
        img = method(1)
        _infer_bookends(img)
```

Across a few MCD files, this yields:
```
Slide
Buffer of length 813076 contains a JPEG from 0 to 812915 (161 extra bytes)
Panorama
Buffer of length 19625792 contains a PNG from 0 to 19625631 (161 extra bytes)
Before_Ab
Buffer of length 20798559 contains a PNG from 0 to 20798398 (161 extra bytes)
After_Ab
Buffer of length 17358666 contains a PNG from 0 to 17358505 (161 extra bytes)
```

**Comment by plankter** [comment]
Fixed in version 2.1.3.
