### ISSUE TITLE
Wrong ROI coordinates for new Fluidigm software versions

### ISSUE THREAD

**Issue by jwindhager** [BodenmillerGroup/imctools#104]
imctools version: 2.1.0  
Python version: 3.9.1  
Operating System: Ubuntu 20.04.1 LTS

The ROI coordinate fix is only applied to old Fluidigm software versions: https://github.com/BodenmillerGroup/imctools/blob/c7238b76c8b639d3777aa91a2326cf91891ee3ed/imctools/io/mcd/mcdxmlparser.py#L115-L120

The code doesn't work correctly for current Fluidigm software versions. This isn't future-proof and a fix is urgently needed.

**Comment by plankter** [comment]
This is an issue we had back then: Correct Fluidigm's comma fault #72

**Comment by plankter** [comment]
I see two options: either I remove version check completely (then we may have problems with future `fixed` versions), or I update the version number to the latest known version, which is broken.

**Comment by plankter** [comment]
Fixed in 2.1.3
