### ISSUE TITLE
ome2histocat stripps .tiff file ending from masks

### ISSUE THREAD

**Issue by votti** [BodenmillerGroup/imctools#111]
Hi,

There is a bug that crept in during the migration to os.path to pahtlib:

Path.stem is the filename without the file extension:
https://github.com/BodenmillerGroup/imctools/blob/e546bd3e452a1fc8f6be53c45f37d13f5c960722/imctools/converters/ome2histocat.py#L71

What you would like to use here is the equivalent to os.path.basename - Path.name:
https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.name

This caused the following issue in the pipeline as masks are now written without file extension:
https://github.com/BodenmillerGroup/ImcSegmentationPipeline/issues/71

@plankter Could you look into this?

Best, Vito

**Comment by plankter** [comment]
Thank you, Vito! I'll prepare a new release tomorrow.

**Comment by plankter** [comment]
Fixed in v 2.1.7
