### ISSUE TITLE
Value Error: No session JSON files available

### ISSUE THREAD

**Issue by marinabroz** [BodenmillerGroup/imctools#112]
* imctools version: 2.1.7
* Python version: 3.9
* Operating System: Windows 10

I am trying to run imc_preprocessing pipeline in a juypter notebook. trying to run the following:

exportacquisitioncsv.export_acquisition_csv(folder_path_ome, output_folder=folder_path_cp_input)

and the following error is returned:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-20-afa1355df6e6> in <module>
----> 1 exportacquisitioncsv.export_acquisition_csv(folder_path_ome, output_folder=folder_path_cp_input)

~\miniconda3\envs\ImcSegmentationPipeline\lib\site-packages\imctools\converters\exportacquisitioncsv.py in export_acquisition_csv(root_folder, output_folder, output_name)
     38     session_files = glob.glob(os.path.join(root_folder, f"*/*{SESSION_JSON_SUFFIX}"), recursive=True)
     39     if len(session_files) == 0:
---> 40         raise ValueError("No session JSON files available.")
     41 
     42     stack = []

ValueError: No session JSON files available.

**Comment by adoppeldy** [comment]
Hey, I actually have the exact same issue on a Mac m1 2020. Same software versions. 
Help would be much appreciated!

**Comment by votti** [comment]
Hi,

While the error message is arguably not very informative, this error happens if there was no image converted in the previous **mcdfolder2imcfolder** step.
Usually this happens because paths to the raw data folders containing the **mcd** fukes not set correctly.

**Comment by adoppeldy** [comment]
Hey Lotti,
thanks for your reply. I managed to solve the issue myself, it had to do with the folder structure as you said. Thanks!
