### ISSUE TITLE
imctools.scripts

### ISSUE THREAD

**Issue by jsymington** [BodenmillerGroup/imctools#118]
* imctools version: 2.1.8
* Python version: 3.9.7
* Operating System: Mac OS 

### Description
I am trying to run the imctools pipeline on jupyter notebook through anaconda. I keep getting the below error telling me that module imctools.scripts does not exist. This happens when I have tried running the pipeline on both my mac and my windows computer. I wondered if I haven't installed everything correctly

<img width="1117" alt="Screenshot 2022-03-22 at 16 18 48" src="https://user-images.githubusercontent.com/102165171/159678650-0f447f58-d662-434a-a4f1-aeca06da96d4.png">

**Comment by nilseling** [comment]
Hi @jsymington 
you are using an outdated version of the notebook. Please refer to the current one here: https://github.com/BodenmillerGroup/ImcSegmentationPipeline/blob/main/scripts/imc_preprocessing.ipynb

**Comment by jsymington** [comment]
Thank yoU!

Jake
