### ISSUE TITLE
masscolumn and metalcolumn in ometiff2analysis.py

### ISSUE THREAD

**Issue by smaffiol** [BodenmillerGroup/imctools#23]
This part is confusing me [lines 20-24]:
if masscolumn is None:
      metalcolumn = metalcolumn
      selmetals = [str(n) for s, n in zip(selected, pannel[metalcolumn]) if s]
else:
      selmass = [str(n) for s, n in zip(selected, pannel[masscolumn]) if s]

3 things:
1. 'metalcolumn = metalcolumn' what for ?
2. you're checking whether masscolumn is None but then using metalcolumn without checking whether it is None or not
3. What is both metalcolumn and masscolumn are None ?

S.

**Comment by votti** [comment]
1. Pretty sure this is an artefact remaining from either a debugging/or variable renaming. This should definitely be removed.
2. I am not explicitly checking for it and relying on pandas of throwing an error. Definitely not good practice and should be done explicitly.
3. The logic of the function should be:
```
If pannelcsv is None:
   returns a .tiff with containing all the channels of the acquisition
   # in this case metalcolumn and massscolumn can be unspecified
else:
   load pannel with filename pannelcsv
   if the pannel has only 1 column:
           # assume the csv is just a list of metal
           return a tiff containing the channels specified in the pannel
           # in this case metalcolumn and massscolumn can be unspecified
  else:
          # asssumes the csv is a table, thus needs a specification
          # which is the  metalcolumn or masscolumn
          if masscolumn is None:
                 # requires that the metalcolumn needs to be specifiec
                return a tiff containing the channels specified in the metalcolumn
          else:
                return a tiff containing the channels specified in the masscolumn

```
Thus it depends on 
a) if pannelcsv is None -> metalcolumn and massscolumn can be None
b) the pannel is a 1 column csv -> metalcolumn and massscolumn can be None
c) the pannel has multiple columns -> either  metalcolumn and massscolum need be not None

The code readability and error checks should be definitely improved here.
