### ISSUE TITLE
Change `bigtiff` default

### ISSUE THREAD

**Issue by votti** [BodenmillerGroup/imctools#32]
Originally I thought we would need bigtiff (can be over 4gb/image) in IMC - however until now I never encountered a file close to that and bigtiffs are generally not widely compatible.

I would thus like to change the default for the `tiffwriter` to `bigtiff = False`.

No break in compatibility is anticipated for this change, except if somebody really has a single image that is over 4gb in size.

Any opinions?

**Comment by DenisSch** [comment]
I have encounter IMC (and non IMC) files larger than 4GB. FYI
