### ISSUE TITLE
gc3pie sub-package

### ISSUE THREAD

**Issue by plankter** [BodenmillerGroup/imctools#50]
It seems that gc3pie sub-package https://github.com/BodenmillerGroup/imctools/tree/master/imctools/gc3pie isn't used at the moment. Should it be deleted from master branch?

**Comment by smaffiol** [comment]
+1 to remove

S.

Il giorno lun 21 gen 2019 alle ore 11:46 Anton Rau <notifications@github.com>
ha scritto:
