### ISSUE TITLE
Deal with temporary files in `omefolder2micatfolder`

### ISSUE THREAD

**Issue by votti** [BodenmillerGroup/imctools#57]
Currently the `omefolder2micatfolder` script fails with temporary files.
https://github.com/BodenmillerGroup/ImcSegmentationPipeline/issues/19

This is a common problem (eg https://github.com/BodenmillerGroup/imctools/issues/43).
Maybe it would make sense to do a custom 'listdir' funciton that ignores temporary files and use this instead of `os.listdir`.

**Comment by minhtran1309** [comment]
I also figured the same problem, and I think it better to change all the functions ( there are two files with this function script/ome2micat.py and script/imc2tiff.py)  `os.listdir(...)` into `glob.glob(os.path.join(path, '*'))`

**Comment by votti** [comment]
Thanks for the suggestion!
That seems indeed to be a great way to ignore hidden files that I have
missed so far.
(Ref: https://stackoverflow.com/a/7099342).

I will implement this sometimes this week.

**Comment by plankter** [comment]
Fixed in version 1.0.6
