### ISSUE TITLE
wrong output of images from MCD

### ISSUE THREAD

**Issue by SchulzDan** [BodenmillerGroup/imctools#62]
from the new acquisition software 7.0 I have obtained MCD files which both contain multiple ROIs but some ROIs are corrupt. The OMEtiffs, tiffs and single tiffs all do not show the correct image. the dimensions are way off and the content is distorted.
When opening the txt files in the MCDviewer software from Fluidigm the images get displayed correctly.
Anton has the data for investigation.

**Comment by votti** [comment]
@plankter  Any follow up on this?
Can this issue be closed?

**Comment by plankter** [comment]
I think it is fixed now, as far as i remember. Unfortunately i don't have test file to check this.

**Comment by votti** [comment]
Then lets close it :)
