### ISSUE TITLE
Revisit OME-TIFF writing

### ISSUE THREAD

**Issue by jwindhager** [BodenmillerGroup/imctools#63]
I think the OME-TIFF generation should be revisited, for these reasons:
- The default OME-XML from the `bioformats` package is flawed (e.g. see the "old format string-s" in the namespace of `StructuredAnnotations`) and sets some default values that aren't required by the OME-TIFF XML schema
- Including a copy of the bioformats package is unnecessary, as the OME-TIFF standard provides an XSD which can be used to validate the custom header independent of the `bioformats` package
- The current implementation of `TiffWriter` doesn't support 3D images and pixel sizes != 1
- Some `tifffile.imwrite` arguments (i.e., standard TIFF properties) are not (fully) supported, including `acquisitiondate` and `resolution`
- The file extension isn't enforced, which I think would be good practice to discriminate between "ImageJ" and OME TIFFs
- Documentation on function parameters such as `compression` is wrong/incomplete
- Function parameter values are not checked (e.g. `assert bigtiff != imagej`)

IMO, writing OME-TIFFs is a core functionality that should be fully and comprehensively supported by this library. For reference, I implemented some of the functionality here: https://github.com/BodenmillerGroup/serial-ablation/blob/master/src/serial_ablation/image_reconstruction.py (see the `write_tiff` function). I would be happy to contribute this (in a modified/more generic version) to a new `imctools` release.

**Comment by votti** [comment]
I think most of this could be addressed by using the `xtiff` library to write out ome tiffs?

**Comment by jwindhager** [comment]
Agreed. Closing.
