### ISSUE TITLE
Allow in-memory extraction of slide/panorama/ablation images

### ISSUE THREAD

**Issue by jwindhager** [BodenmillerGroup/imctools#73]
Currently, slide/panorama/ablation images stored in the MCD files can only be extracted to disk. It would be desirable to give users the option to write them to custom output, e.g. StringIO, or allow direct binary data extraction (similar to `_get_buffer`). This would enable in-memory processing without a need for temporary files on disk, which is quite important. Ideally, one would also provide a function that tries to automatically convert the embedded images into numpy arrays (for supported data formats only), e.g. using PIL.

**Comment by plankter** [comment]
Implemented in v2.1.0
