### ISSUE TITLE
Wrong initialization of panorama coordinates

### ISSUE THREAD

**Issue by jwindhager** [BodenmillerGroup/imctools#74]
Consider the following code and output for a `panorama` instance:
```python3
x1, y1 = float(panorama.metadata['SlideX1PosUm']), float(panorama.metadata['SlideY1PosUm'])
x2, y2 = float(panorama.metadata['SlideX2PosUm']), float(panorama.metadata['SlideY2PosUm'])
x3, y3 = float(panorama.metadata['SlideX3PosUm']), float(panorama.metadata['SlideY3PosUm'])
x4, y4 = float(panorama.metadata['SlideX4PosUm']), float(panorama.metadata['SlideY4PosUm'])
x = min(x1, x2, x3, x4)
y = min(y1, y2, y3, y4)
width = max(x1, x2, x3, x4) - x
height = max(y1, y2, y3, y4) - y
print(x, y, width, height)
print(panorama.start_position_x, panorama.start_position_y, panorama.width, panorama.height)
```
```
-55.715 112.972 75000.0 25219.775999999998
-55.715 25332.748 75000.0 25219.775999999998
```
It looks like the current implementation assumes a specific order of the four points in the MCD Panorama metadata. However, to my knowledge, the order is not guaranteed. This might explain the discrepancies observed above.

**Comment by plankter** [comment]
In your example starting point will be left-bottom point (X3) and i assume it should be left-top (X1). This is a question of a coordinate grid. In order to avoid conclusion, probably it is better to store coordinates of all 4 individual points (like in raw data), instead of starting point and width/height.

**Comment by jwindhager** [comment]
If a rectangle aligned with the coordinate system can be assumed, the computation above will give correct x, y, width, height. Otherwise, I agree re storing the four points individually.
