### ISSUE TITLE
get_image_stack throws TypeError if acquisition is empty

### ISSUE THREAD

**Issue by jwindhager** [BodenmillerGroup/imctools#76]
get_image_stack methods (e.g. `get_image_stack_by_names`) throw TypeErrors if the acquisition is empty (there should probably be a check for `Acquisition.is_valid`). Also, there is a typo in the log message in `_get_acquisition_raw_data`.

**Comment by jwindhager** [comment]
Also, I'm not sure whether it's a good idea to store `is_valid` with the `Acquisition` instead of the `AcquisitionData` object. This would essentially mean that users have to call `get_acquisition_data` before this field is populated.

**Comment by plankter** [comment]
Logic is little bit different here: to understand if acquisition is valid, one has to try to read its binary data first (if it is possible, then acquisition is valid). This step is always done during conversion to IMC folder format, which is a "real" format that has to be used, not original `mcd` files. After such conversion, the validity status is serialized as part of `Acquisition` data, which allows to check the validity without reading binary data again.

**Comment by jwindhager** [comment]
I understand that this information should be serialized.

At the same time, the following code looks a bit hacky to me:
```python3
acquisition_data = mcd_parser.get_acquisition_data(acquisition.id)
if acquisition.is_valid:
    pass  # continue here
```

* `Acquisition.is_valid` is set to `True` before reading the binary file. It should probably be `None` instead, as the information is not available at this point.
* One has to check the acquisition passed to `get_acquisition_data` in order to check the success of the operation. IMO it would be cleaner if this could be done using the `AcquisitionData` object returned from that operation.
