### ISSUE TITLE
Remove `add_sum` functionality from `omefile_2_analysisfolder`

### ISSUE THREAD

**Issue by votti** [BodenmillerGroup/imctools#78]
The current `add_sum` functionality is still a relict from the time `imctools` also contained image processing capabilities.

Given that the sum can also be added in Cellprofiler, this option should be removed in V2.

**Comment by nilseling** [comment]
Is this really fixed? I can confirm that no channel sum is added to the file. However, the `omefolder_2_analysisfolder` function still requires entries of length 3 rather than of length 2.
