### ISSUE TITLE
imctools version 2 documentation link broken

### ISSUE THREAD

**Issue by algebio** [BodenmillerGroup/imctools#84]
Hi 

I got error 404 when I try to open this link:

Version 2.x documentation: https://bodenmillergroup.github.io/imctools

Is there any other resource to learn more about imctools version 2?

Regards
Juan

**Comment by plankter** [comment]
Dear Juan,

Version 2 isn't publicly released yet, that's why documentation is still missing.

Best regards,
Anton

**Comment by algebio** [comment]
Oh I see. Thanks for the info, Anton. I got excited too soon. 

I'll give it a go without documentation or safety net.. wish me luck.

Regards
Juan
