### ISSUE TITLE
tifffile vs xtiff for v2

### ISSUE THREAD

**Issue by jwindhager** [BodenmillerGroup/imctools#87]
As [tifffile](https://github.com/cgohlke/tifffile) seems to be adding support for writing OME-TIFF files, we should review the value added by using [xtiff](https://github.com/BodenmillerGroup/xtiff) for v2. Maybe we can ask @cgohlke about the current status/future plans in this regard (and also about his assessment re tifffile vs xtiff for our usecase, in case he knows xtiff).

**Comment by cgohlke** [comment]
Compared to tifffile, it looks like xtiff does not support multiple series, other possible dimension orders, or more than 5 dimensions. On the other hand, tifffile's OME writing is not yet widely used/proven. Tifffile currently supports only the Image, AcquisitionDate, and Description elements of the OME model...

**Comment by jwindhager** [comment]
Thank you for your assessment, @cgohlke! Based on this, we should probably continue to use xtiff for now, as support for the `Channel` element is required, the xtiff XML output is validated & tested and xtiff performs some additional sanity checks for our use case. This is to be re-assessed in the future, once the OME support in tifffile is stable & proven.
