### ISSUE TITLE
pandas version pinning

### ISSUE THREAD

**Issue by jwindhager** [BodenmillerGroup/imctools#89]
Is it really necessary to pin pandas to versions >= 1.1.0? At this point in time, this is a quite strict requirement that causes conflicts with other packages that I use

**Comment by plankter** [comment]
Good point, i'll remove strict pinning for pandas.

**Comment by jwindhager** [comment]
Not sure, haven't investigated further. If you want, you can have a look at the slidescanner repo, some packages in its requirements seem to depend on pandas 1.0.5.

**Comment by plankter** [comment]
Version constraints are weakened.
