### ISSUE TITLE
Combine several ROIs into one

### ISSUE THREAD

**Issue by laufre** [BodenmillerGroup/imctools#95]
Hello,

I was wondering whether there is an elegant way to combine several ROIs on the level of the .mcd file into one, without loosing any information. 
Due to challenges in acquisition we face the problem of having a lot of small ROIs. We are now looking for a way to combine those small ROIs into a single large ROI for further analysis.
We would appreciate any ideas or input on how to do that! 

Thanks,

**Comment by jwindhager** [comment]
Hi @laufre.

to correctly align multiple acquisitions of one slide into a single image, you will need to use the "slide-global" coordinate system of the machine. Assuming you are doing your downstream analysis in Python, you could e.g. first create a (zero-filled) numpy array representing the slide image and then fill that array with the individual acquisitions according to their coordinates relative to the slide. The slide coordinates of an acquisition can be found in the acquisition's metadata, e.g. `Acquisition.roi_start_x_pos_um`. Note that this is a floating point number, so you will need to be careful with the precise coordinates you are using.

However, this approach will likely (unnecessarily) require a lot of memory, unless the ROIs are very close to each other. Also, as even background pixels often contain noise (larger than zero), doing this will skew your statistics computed for the joint image. So, if possible, I recommend to instead adapt your downstream analysis workflow to allow for multiple small ROIs.  Alternatively, you could use semi-sparse data structures to only store the data that is actually available (e.g. by using x/y axis-labeled structures such as xarray DataArray's). But I'd assume this will require quite some implementation effort...

Btw, if you only want to plot the multiple ROIs in one image using matplotlib's `imshow`, you can use the `extent` parameter to specify slide coordinates.

Hope this helps!

**Comment by votti** [comment]
Hi,

Modifying the `.mcd` file is definitely not possible, as it is a proprietary file format that we are legally not allowed to modify with 3rd party tools. Thus if you want this functionallity for `.mcd` files there is no other way than asking Fluidigm to provide a tool to do this.

I second @jwindhager s suggestion to try to accommodate the downstream analysis and visualization to support visualizing/normalizing/... multiple ROIs simultaneously using the coordinates from the metadata.

The 'earliest' point where one could think of modifying 'raw' data before downstream analysis, is at the point of generating .ome.tiff folders (assuming you use: https://github.com/BodenmillerGroup/ImcSegmentationPipeline). There one could think about combining multiple `.ome.tiffs`.
However even there this would be a rather delicate than elegant operation as:
a) the metadata would also need to be adapted
b) one almost certainly would induce technical artefacts at the border between ROI fragments that might induce subtle artefacts in the downstream analysis (e.g. slightly higher/lower signal intensity at such borders).

**Comment by laufre** [comment]
Thank you so much for your quick and helpful answers! 
We will discuss this and I'll probably come back for your advice. You've been a big help :)
