### ISSUE TITLE
NotADirectoryError: [Errno 20] Not a directory: '../../data/ometiff/.DS_Store/.DS_Store_Acquisition_meta.csv'

### ISSUE THREAD

**Issue by laufre** [BodenmillerGroup/imctools#98]
Hi,

During the imc data preprocessing I'm running into an error at the "Generate a csv with all the acquisition metadata" Step ,that I can't fix:

NotADirectoryError: [Errno 20] Not a directory: '../../data/ometiff/.DS_Store/.DS_Store_Acquisition_meta.csv'

There is no .DS_Store in my ometiff folder and otherwise I think my folder structure should be correct.I am using Mac OS Big Sur.

Thanks for your help!

**Comment by plankter** [comment]
Could you tell please which `imctools` version do you have?

**Comment by laufre** [comment]
It tells me Version 0.0.4, but I'm not sure if that can be right...

pip show imctools
Name: imctools
Version: 0.0.4
Summary: Tools to handle IMC data
Home-page: https://github.com/bodenmillerlab/imctools
Author: Vito Zanotelli
Author-email: vito.zanotelli@uzh.ch
License: imctools
Location: /Applications/anaconda3/envs/imctools/lib/python3.6/site-packages

**Comment by votti** [comment]
Hi!
Sorry, the version description in `imctools` v1 is a bit weird.

Unfortunately `imctools` v1 has some issues with `hidden` files and folders (folders starting with a `.` that are not shown in file browsers). You may delete them using your terminal using `rm -R data/ometiff/.DS_Store` in your case.

These issues should be gone using `imctools` v2. I am currently close to releasing a stable version of the `ImcSegmentationPipeline` using `imctools v2 and also the latest Cellprofiler: https://github.com/BodenmillerGroup/ImcSegmentationPipeline/tree/imctools2

This should be already usable, so I would suggest you use following this.

I hope this helps!

H

**Comment by laufre** [comment]
I already tried deleting, which unfortunately didn't work. I used windows 10 instead, which worked, so I'll use this way in the future. I#m looking forward to the new pipeline with imctools V2!
