### ISSUE TITLE
Adding clear specification of the 'ome' folder

### ISSUE THREAD

**Issue by votti** [BodenmillerGroup/imctools#99]
* imctools version: 2
* Python version: Na
* Operating System: Na

### Description

It would be important that we release a formal specification of:
a) the `ome.tiff` we generate
b) the content of the `ome` folder (e.g. all the metadata files and what each entry means).

This should make it easier for others to work with this data format.

**Comment by nilseling** [comment]
I agree that this would be nice. It could be added as a [sub-page to the ImcSegmentationPipeline docs](https://bodenmillergroup.github.io/ImcSegmentationPipeline/prepro.html) somewhere if you don't want it do be added to the imctools docs.
